version: "3"
services:
  nextcloud:
    container_name: nextcloud
    environment:
      - TZ="${TZ}"
      - PUID=1000
      - PGID=1000
    image: linuxserver/nextcloud:latest
    networks:
      - mariadb
    ports:
      - 4443:443/tcp
    restart: always
    volumes:
      - ~/nextcloud_config:/config
      - ~/nextcloud_data:/data
      
networks:
  mariadb:
