version: "3"
services:
  duckdns-tdouble:
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - AUDIT_CONTROL
      - BLOCK_SUSPEND
      - DAC_READ_SEARCH
      - IPC_LOCK
      - IPC_OWNER
      - LEASE
      - LINUX_IMMUTABLE
      - MAC_ADMIN
      - MAC_OVERRIDE
      - NET_ADMIN
      - NET_BROADCAST
      - SYSLOG
      - SYS_ADMIN
      - SYS_BOOT
      - SYS_MODULE
      - SYS_NICE
      - SYS_PACCT
      - SYS_PTRACE
      - SYS_RAWIO
      - SYS_RESOURCE
      - SYS_TIME
      - SYS_TTY_CONFIG
      - WAKE_ALARM
    container_name: duckdns-tdouble
    entrypoint:
      - /init
    environment:
      - TOKEN=68ff8d87-d146-45eb-a9f6-d3051c097ef9
      - TZ=America/Los_Angeles
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - 'PS1=$(whoami)@$(hostname):$(pwd)\$ '
      - HOME=/root
      - TERM=xterm
      - S6_BEHAVIOUR_IF_STAGE2_FAILS=2
      - SUBDOMAINS=tdouble
    hostname: d9698d930d5b
    image: linuxserver/duckdns:latest
    ipc: private
    labels:
      build_version: 'Linuxserver.io version:- 2da349aa-ls57 Build-date:- 2020-09-19T15:34:27-04:00'
      maintainer: aptalca
    logging:
      driver: json-file
      options: {}
    mac_address: 02:42:ac:11:00:03
    networks:
      bridge:
        aliases:
    restart: always
    volumes:
      - duckdns_config:/config
networks:
  bridge:
    external: true
