version: "3"
services:
  watchtower:
    command:
      - --cleanup
    container_name: watchtower
    entrypoint:
      - /watchtower
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    expose:
      - 8080/tcp
    image: containrrr/watchtower
    ipc: private
    labels:
      com.centurylinklabs.watchtower: true
    logging:
      driver: json-file
      options: {}
    networks:
      bridge:
        aliases:
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  bridge:
    external: true
