version: '2'
services:
  cloudflare-npm:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=xxxxxxx
      - EMAIL=<CF email>
      - ZONE=example.com
      - SUBDOMAIN=npm
      - PROXIED=true
  cloudflare-onlyoffice:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=xxxxxxx
      - EMAIL=<CF email>
      - ZONE=example.com
      - SUBDOMAIN=onlyoffice
      - PROXIED=true
  cloudflare-nextcloud:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=xxxxxxx
      - EMAIL=<CF email>
      - ZONE=example.com
      - SUBDOMAIN=nextcloud
      - PROXIED=true
      
