---
version: "2"
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /home/rightified/nextcloud_config:/config
      - nextcloud_data:/data
    depends_on:
      - mariadb
    restart: unless-stopped
    ports:
      - "4443:443"
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=******PASSWORD*******
      - TZ=America/Los_Angeles
    volumes:
      - mariadb_config:/config
    restart: unless-stopped
  onlyoffice:
    image: alehoho/oo-ce-docker-license
    container_name: onlyoffice
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data
      - onlyoffice_custom:/usr/share/fonts/truetype/custom
      - onlyoffice_lib:/var/lib/onlyoffice
      - onlyoffice_postgresql:/var/lib/postgresql
      - onlyoffice_rabbitmq:/var/lib/rabbitmq
      - onlyoffice_redis:/var/lib/redis
      - onlyoffice_log:/var/log/onlyoffice
    restart: always
    ports:
      - "8080:80"
