version: "3"
services:
  portainer-ce:
    container_name: portainer-ce
    image: portainer/portainer-ce
    ports:
      - 8000:8000/tcp
      - 9000:9000/tcp
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  
volumes:
  portainer_data:
