version: "3"
services:
  mariadb:
    container_name: mariadb
    environment:
      - TZ="${TZ}"
      - MYSQL_DATABASE="${MYSQL_DATABASE}"
      - MYSQL_USER="${MYSQL_USER}"
      - MYSQL_PASSWORD="${MYSQL_PASSWORD}"
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
    image: linuxserver/mariadb
    networks:
      - mariadb
    restart: always
    volumes:
      - ~/mariadb_config:/config
networks:
  nextcloud:
    external: true
