version: "3"
services:
  mariadb:
    container_name: mariadb
    environment:
      - TZ="${TZ}"
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
    image: linuxserver/mariadb
    networks:
      - mariadb
    restart: always
    volumes:
      - ~/mariadb_config:/config
networks:
  mariadb:
    external: true
