version: "3"
services:
  duckdns:
    container_name: "duckdns-${SUBDOMAINS}"
    environment:
      - TOKEN="${TOKEN}"
      - TZ="${TZ}"
      - SUBDOMAINS="${SUBDOMAINS}"
    image: linuxserver/duckdns:latest
    networks:
      bridge:
        aliases:
    restart: always
    volumes:
      - duckdns_config:/config
      
networks:
  bridge:
    external: true
volumes:
  duckdns_config:
